name = "origins-with-perspective"
main = "worker.js"
compatibility_date = "2025-08-30"

# Static assets configuration for Wrangler 4.x
[assets]
directory = "./dist"
binding = "ASSETS"

# GitHub repository integration
# This worker is automatically deployed via GitHub Actions
# Repository: https://github.com/bryanfawcett/origins-with-perspective
# Manual deployments are disabled - use GitHub for deployments
